### ISSUE TITLE
Unable to resolve setup-xc@v1

### ISSUE THREAD

**Issue by miyamo2** [joerdav/setup-xc#2]
Hello, @joerdav 

When I define a step as described in the README, the following error occurs.
```
Unable to resolve action `joerdav/setup-xc@v1`, unable to find version `v1`
```

This is because only the tags `v0.0.2` and `v0.0.3` currently exist.

Users can proactively solve this problem by modifying the version specification as follows
```
- uses: joerdav/setup-xc@v0.0.3
```

However, as a user, it would be nice to be able to use major version tags such as `v0` and `v1`.

> Move the major version tag (such as v1, v2) to point to the Git ref of the current release. For more information, see "[Git basics - tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)."

https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management

Thank you.

**Comment by joerdav** [comment]
Thanks, good point! I've just pushed v1
